obj-m := al_eth.o

al_eth-y := al_eth_group_lm.o al_eth_main.o al_eth_sysfs.o al_hal_eth_kr.o \
            al_hal_eth_main.o al_hal_iofic.o al_hal_serdes_25g.o al_hal_serdes_hssp.o \
            al_hal_udma_config.o al_hal_udma_debug.o al_hal_udma_iofic.o \
            al_hal_udma_main.o al_init_eth_kr.o al_init_eth_lm.o al_serdes.o \
            alpine_group_lm.o alpine_serdes.o kcompat.o
